src/main/resources/application.yml

* cosmosdb/mongodb idle timeout limit fixed
* cosmosdb/mongodb min pool sizes fixed

Fix mongo idle timeout (#6)

---

helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml
pom.xml
src/main/java/it/gov/pagopa/initiative/statistics/service/BaseStatisticsEvaluationService.java
src/main/resources/application.yml
src/test/java/it/gov/pagopa/initiative/statistics/events/consumers/BaseStatisticsMessagesListenerTest.java
src/test/java/it/gov/pagopa/initiative/statistics/repository/InitiativeStatAtomicOpsRepositoryTest.java

Reverts pagopa/idpay-initiative-statistics#22

Revert "IDP-51-attivazione-autoscaling"

---

src/test/java/it/gov/pagopa/common/mongo/repository/BaseMongoRepositoryIntegrationTest.java
src/test/java/it/gov/pagopa/common/mongo/repository/BaseMongoRepositoryTestIntegrated.java

* IDP-1106 findById optimize to be run on cosmosDB
* extending coverage

feat: IDP-1106 findById optimize to be run on cosmosDB (#48)

---

helm/values-dev.yaml

**List of changes**
-  [IDP-1641](https://pagopa.atlassian.net/browse/IDP-1641) Aligning initiative delete logs
[IDP-1641]: https://pagopa.atlassian.net/browse/IDP-1641?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Promote to UAT

---

.github/workflows/anchore.yml
Dockerfile
pom.xml

**Description**
The purpose of this PR is to solve the vulnerabilities(CVE) with status high
**List of changes**
- Docker file
- Anchore
- Update dependencies
**Motivation and context**
**How has this been tested?**
**Types of changes**
**Checklist:**

feat: IDP-1498-risoluzione-cve-idpay-initiative-statistics

---

pom.xml
src/main/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeAutomaticRetryAspect.java
src/main/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryable.java
src/main/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryableAspect.java
src/main/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryer.java
src/main/java/it/gov/pagopa/common/mongo/retry/exception/MongoRequestRateTooLargeRetryExpiredException.java
src/main/java/it/gov/pagopa/common/web/exception/MongoExceptionHandler.java
src/main/resources/application.yml
src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeAutomaticRetryAspectTest.java
src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryIntegrationTest.java
src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryerTest.java
src/test/java/it/gov/pagopa/common/web/exception/ErrorManagerTest.java
src/test/java/it/gov/pagopa/common/web/exception/MongoExceptionHandlerTest.java

**Description**
Added management 429 for idpay-initiative-statistics
**List of changes**
**Motivation and context**
**How has this been tested?**
**Types of changes**
**Checklist:**

feat: IDP-1541-gestione-429-per-idpay-initiative-statistics

---

.devops/deploy-pipelines.yml
.github/CODEOWNERS
.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/anchore.yml
.github/workflows/pr-title.yml
.github/workflows/release.yml
.releaserc.json
CODEOWNERS
Dockerfile
helm/Chart.lock
helm/Chart.yaml
helm/values.yaml
pom.xml

- upgrade helmchart to 2.8.0
- update anchore action triggers (on push and workflow_dispatch)
- add proper .releaserc.json + bump to semantic-release v4
- add pull request template
- fix anchor skip steps
- fix codeowners

chore: [IDP-1723] devops fixes

---

.devops/deploy-pipelines.yml
.github/CODEOWNERS
.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/anchore.yml
.github/workflows/pr-title.yml
.github/workflows/release.yml
.releaserc.json
CODEOWNERS
Dockerfile
helm/Chart.lock
helm/Chart.yaml
helm/values.yaml
pom.xml
src/main/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeAutomaticRetryAspect.java
src/main/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryable.java
src/main/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryableAspect.java
src/main/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryer.java
src/main/java/it/gov/pagopa/common/mongo/retry/exception/MongoRequestRateTooLargeRetryExpiredException.java
src/main/java/it/gov/pagopa/common/web/exception/MongoExceptionHandler.java
src/main/resources/application.yml
src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeAutomaticRetryAspectTest.java
src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryIntegrationTest.java
src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryerTest.java
src/test/java/it/gov/pagopa/common/web/exception/ErrorManagerTest.java
src/test/java/it/gov/pagopa/common/web/exception/MongoExceptionHandlerTest.java

* feat: IDP-1498-risoluzione-cve-idpay-initiative-statistics (#67)
* IDP-1498-risoluzione-cve-idpay-initiative-statistics
* IDP-1498-risoluzione-cve-idpay-initiative-statistics
* IDP-1498-risoluzione-cve-idpay-initiative-statistics
* IDP-1498-risoluzione-cve-idpay-initiative-statistics update spring-kafka
* feat: IDP-1541-gestione-429-per-idpay-initiative-statistics (#69)
* IDP-1541-gestione-429-per-idpay-initiative-statistics
* IDP-1541-gestione-429-per-idpay-initiative-statistics
* chore: [IDP-1723] devops fixes (#70)
* devops fixes
* bump to 1.0.0
---------
[IDP-1723]: https://pagopa.atlassian.net/browse/IDP-1723?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: devops fixes (#71)

---

.devops/deploy-pipelines.yml
.github/CODEOWNERS
.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/anchore.yml
.github/workflows/pr-title.yml
.github/workflows/release.yml
.releaserc.json
CODEOWNERS
Dockerfile
helm/Chart.lock
helm/Chart.yaml
helm/values.yaml
pom.xml
src/main/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeAutomaticRetryAspect.java
src/main/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryable.java
src/main/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryableAspect.java
src/main/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryer.java
src/main/java/it/gov/pagopa/common/mongo/retry/exception/MongoRequestRateTooLargeRetryExpiredException.java
src/main/java/it/gov/pagopa/common/web/exception/MongoExceptionHandler.java
src/main/resources/application.yml
src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeAutomaticRetryAspectTest.java
src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryIntegrationTest.java
src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryerTest.java
src/test/java/it/gov/pagopa/common/web/exception/ErrorManagerTest.java
src/test/java/it/gov/pagopa/common/web/exception/MongoExceptionHandlerTest.java

> ### Description
- [IDP-1723](https://pagopa.atlassian.net/browse/IDP-1723) initiative statistics
- [IDP-1541](https://pagopa.atlassian.net/browse/IDP-1541) Gestione 429 per idpay-initiative-statistics
- [IDP-1498](https://pagopa.atlassian.net/browse/IDP-1498) Risoluzione CVE idpay-initiative-statistics
> ### List of changes
> ### Motivation and context
> ### Aggregation level
> * [x]  Test case
> * [ ]  Test suite
> 
> ### Test type
> * [ ]  Functional test
> * [ ]  Smoke test
> * [ ]  End to end
> * [ ]  Performance
> 
> ### Type of changes
> * [ ]  Add new test case/suite
> * [ ]  Modify existing test case/suite
> 
> ### Test Results
> * [x]  Success
> * [ ]  Failure
> * [ ]  Poor performance
> * [ ]  Good performance
> 
> ### Did you update secrets accordingly?
> * [ ]  Yes
> * [x] …

feat: Promote to UAT

---

.github/workflows/anchore.yml

chore: fix anchore skip step (#77)

---

.github/workflows/anchore.yml

chore: Release prod

---

Dockerfile

IDP-1760 fix new critical CVE CVE-2022-48174

fix: IDP-1760 fixCve

---

src/main/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeApiRetryable.java
src/main/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeAutomaticRetryAspect.java
src/main/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryableAspect.java
src/main/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryer.java
src/main/java/it/gov/pagopa/common/web/exception/MongoExceptionHandler.java
src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeAutomaticRetryAspectTest.java
src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryIntegrationTest.java
src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryerTest.java
src/test/java/it/gov/pagopa/common/web/exception/MongoExceptionHandlerTest.java

IDP-1765 allow mongo RequestRateTooLarge exception always retryable for selected API

feat: IDP-1765 selected API retryable

---

src/main/java/it/gov/pagopa/initiative/statistics/dto/events/CommandOperationDTO.java
src/main/java/it/gov/pagopa/initiative/statistics/repository/merchant/counters/MerchantInitiativeCountersOpsRepository.java
src/main/java/it/gov/pagopa/initiative/statistics/repository/merchant/counters/MerchantInitiativeCountersOpsRepositoryImpl.java
src/main/java/it/gov/pagopa/initiative/statistics/repository/merchant/counters/MerchantInitiativeCountersRepository.java
src/main/java/it/gov/pagopa/initiative/statistics/service/commands/CommandsMediatorServiceImpl.java
src/main/java/it/gov/pagopa/initiative/statistics/service/commands/ops/DeleteInitiativeService.java
src/main/java/it/gov/pagopa/initiative/statistics/service/commands/ops/DeleteInitiativeServiceImpl.java
src/test/java/it/gov/pagopa/initiative/statistics/events/consumers/CommandsMessagesListenerTest.java
src/test/java/it/gov/pagopa/initiative/statistics/service/commands/ops/DeleteInitiativeServiceImplTest.java

The purpose of this pr is to change the method of deletion from the database from a bulk delete to a paged delete.
- Modified CommandOperationDTO
- Added paged delete method to extended repository
- Modified JUnit tests

fix: IDP-1852-initiativeStatistics_pagedDelete

---

helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml
src/main/java/it/gov/pagopa/initiative/statistics/service/commands/ops/DeleteInitiativeServiceImpl.java
src/main/resources/application.yml
src/test/java/it/gov/pagopa/initiative/statistics/BaseIntegrationTest.java
src/test/java/it/gov/pagopa/initiative/statistics/service/commands/ops/DeleteInitiativeServiceImplTest.java

The purpose of this pr is to change the method of getting parameters from the event dto to the application.yml
- Removed getting parameters from event dto
- Added pagination and delay parameters in application and values yaml
- Fixed Junit tests

fix: IDP-1852-Added pagination and delay to application.yml and values environments. Modified JUnit tests

---

Dockerfile
pom.xml
src/main/java/it/gov/pagopa/common/web/exception/MongoExceptionHandler.java
src/main/resources/application.yml
src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryerTest.java

fix: Idp 2016 fix CVE

---

src/main/java/it/gov/pagopa/common/web/exception/MongoExceptionHandler.java

chore: fixed code smell

---

Dockerfile
pom.xml
src/main/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeAutomaticRetryAspect.java
src/main/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryableAspect.java
src/main/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryer.java
src/main/java/it/gov/pagopa/common/mongo/retry/exception/MongoRequestRateTooLargeRetryExpiredException.java
src/main/java/it/gov/pagopa/common/web/exception/MongoExceptionHandler.java
src/main/resources/application.yml
src/test/java/it/gov/pagopa/common/mongo/DummySpringRepository.java
src/test/java/it/gov/pagopa/common/mongo/repository/BaseMongoRepositoryIntegrationTest.java
src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeAutomaticRetryAspectTest.java
src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryIntegrationTest.java
src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryerTest.java
src/test/java/it/gov/pagopa/common/web/exception/MongoExceptionHandlerTest.java

fix: Release dev

---

.github/CODEOWNERS
src/main/java/it/gov/pagopa/initiative/statistics/service/BaseGenericConsumerService.java
src/test/java/it/gov/pagopa/common/mongo/EmbeddedMongodbTestClient.java
src/test/java/it/gov/pagopa/common/mongo/EmbeddedMongodbTestSyncClient.java
src/test/java/it/gov/pagopa/common/mongo/MongoTestIntegrated.java
src/test/java/it/gov/pagopa/common/mongo/repository/BaseMongoRepositoryIntegrationTest.java
src/test/java/it/gov/pagopa/common/mongo/repository/BaseMongoRepositoryTestIntegrated.java
src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryIntegrationTest.java
src/test/java/it/gov/pagopa/common/mongo/singleinstance/AutoConfigureSingleInstanceMongodb.java
src/test/java/it/gov/pagopa/common/mongo/singleinstance/SingleEmbeddedMongodbAutoConfiguration.java
src/test/java/it/gov/pagopa/common/mongo/singleinstance/SingleInstanceMongodWrapper.java
src/test/java/it/gov/pagopa/initiative/statistics/BaseIntegrationTest.java
src/test/java/it/gov/pagopa/initiative/statistics/events/consumers/CommandsMessagesListenerTest.java
src/test/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
src/test/resources/META-INF/spring/org.springframework.boot.test.autoconfigure.data.mongo.AutoConfigureDataMongo.imports
src/test/resources/mongodbEmbeddedDisabled.properties

chore: IDP-2102 configuring a single mongodb instance for all tests

---

.github/CODEOWNERS
Dockerfile
src/main/java/it/gov/pagopa/initiative/statistics/service/BaseGenericConsumerService.java
src/test/java/it/gov/pagopa/common/mongo/EmbeddedMongodbTestClient.java
src/test/java/it/gov/pagopa/common/mongo/EmbeddedMongodbTestSyncClient.java
src/test/java/it/gov/pagopa/common/mongo/MongoTestIntegrated.java
src/test/java/it/gov/pagopa/common/mongo/repository/BaseMongoRepositoryIntegrationTest.java
src/test/java/it/gov/pagopa/common/mongo/repository/BaseMongoRepositoryTestIntegrated.java
src/test/java/it/gov/pagopa/common/mongo/retry/MongoRequestRateTooLargeRetryIntegrationTest.java
src/test/java/it/gov/pagopa/common/mongo/singleinstance/AutoConfigureSingleInstanceMongodb.java
src/test/java/it/gov/pagopa/common/mongo/singleinstance/SingleEmbeddedMongodbAutoConfiguration.java
src/test/java/it/gov/pagopa/common/mongo/singleinstance/SingleInstanceMongodWrapper.java
src/test/java/it/gov/pagopa/initiative/statistics/BaseIntegrationTest.java
src/test/java/it/gov/pagopa/initiative/statistics/events/consumers/CommandsMessagesListenerTest.java
src/test/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
src/test/resources/META-INF/spring/org.springframework.boot.test.autoconfigure.data.mongo.AutoConfigureDataMongo.imports
src/test/resources/mongodbEmbeddedDisabled.properties

chore: Release dev

---

src/main/java/it/gov/pagopa/common/utils/CommonUtilities.java
src/main/java/it/gov/pagopa/initiative/statistics/controller/InitiativeApiControllerImpl.java
src/main/java/it/gov/pagopa/initiative/statistics/dto/InitiativeStatisticsDTO.java
src/test/java/it/gov/pagopa/initiative/statistics/controller/InitiativeApiControllerTest.java

Fix fields response statistics

Fix: IDP-1342 Uniformare formato dei valori restituiti dagli endpoint di GET delle statistiche

---

Dockerfile
src/main/java/it/gov/pagopa/common/utils/CommonUtilities.java
src/main/java/it/gov/pagopa/initiative/statistics/controller/InitiativeApiControllerImpl.java
src/main/java/it/gov/pagopa/initiative/statistics/dto/InitiativeStatisticsDTO.java
src/test/java/it/gov/pagopa/initiative/statistics/controller/InitiativeApiControllerTest.java

Release dev

---

pom.xml

fix: upgrade pom

---

Dockerfile
pom.xml
src/main/java/it/gov/pagopa/initiative/statistics/config/kafka/BaseKafkaConsumerConfig.java
src/test/java/it/gov/pagopa/common/kafka/KafkaTestUtilitiesService.java
src/test/java/it/gov/pagopa/initiative/statistics/BaseIntegrationTest.java
src/test/java/it/gov/pagopa/initiative/statistics/events/consumers/BaseStatisticsMessagesListenerTest.java
src/test/java/it/gov/pagopa/initiative/statistics/events/consumers/StatisticsMessagesListenerConcurrentTest.java

fix: IDP-2196 fix Cve

---

src/main/java/it/gov/pagopa/initiative/statistics/service/merchant/counters/trx/MerchantTransactionStatisticsServiceImpl.java
src/main/java/it/gov/pagopa/initiative/statistics/service/trx/TransactionEvaluationStatisticsServiceImpl.java
src/main/java/it/gov/pagopa/initiative/statistics/utils/Constants.java

[IDP-2367](https://pagopa.atlassian.net/browse/IDP-2367)
Update the incoming transaction filtering logic to only accept transactions with the status 'REWARDED'.
[IDP-2367]: https://pagopa.atlassian.net/browse/IDP-2367?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: [IPD-2367] Change incoming transaction filtering logic

---

specs/asyncapi.yml

[IDP-2482](https://pagopa.atlassian.net/browse/IDP-2482)
[IDP-2482]: https://pagopa.atlassian.net/browse/IDP-2482?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: [IDP-2482] Async Documentation

---

specs/asyncapi.yml

- Update references on asyncapi.yml

chore: update asycnapi references

---

.grype.yaml
Dockerfile
pom.xml

chore: update tomcat CVE

---

.grype.yaml
Dockerfile
pom.xml
src/test/java/it/gov/pagopa/common/kafka/KafkaTestUtilitiesService.java

- Update amazoncorretto image
- Update spring boot parent version

chore: fix CVE

---

.grype.yaml
Dockerfile
pom.xml
src/test/java/it/gov/pagopa/common/kafka/KafkaTestUtilitiesService.java

This reverts commit d7c370c814532014d10a9514e385889e78b2c230.

chore: revert dependency

---

.grype.yaml
Dockerfile
helm/values-dev.yaml
helm/values-prod.yaml
helm/values-uat.yaml
helm/values.yaml
pom.xml
src/test/java/it/gov/pagopa/common/kafka/KafkaTestUtilitiesService.java

- Fix docker amazoncorretto CVE
- Update dependency version
- Update helm values on DEV, UAT, PROD
[PR](https://github.com/pagopa/idpay-initiative-statistics/pull/139)

chore: promote to UAT

---

.github/CODEOWNERS
Dockerfile
pom.xml

chore: fix cve (#150)

---

pom.xml

chore: [IDP-2676 ]update jdk to 21

---

src/main/java/it/gov/pagopa/initiative/statistics/controller/InitiativeApiControllerImpl.java

fix: update release
